# Generated by Django 5.2 on 2025-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data',
        ),
        migrations.AddField(
            model_name='despesa',
            name='ano',
            field=models.IntegerField(choices=[(2025, 2025), (2026, 2026), (2027, 2027)], default='01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='01', max_length=2),
            preserve_default=False,
        ),
    ]
