# Generated by Django 5.2 on 2025-04-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_remove_despesa_data_despesa_ano_despesa_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='descricao',
        ),
        migrations.CreateModel(
            name='LeituraGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('leitura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.unidade')),
            ],
            options={
                'unique_together': {('unidade', 'mes', 'ano')},
            },
        ),
    ]
