# Generated by Django 5.2 on 2025-04-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_remove_despesa_descricao_leituragas'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='gas_leituras',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='mes',
            field=models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2),
        ),
    ]
