# Generated by Django 5.2 on 2025-04-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_despesa_gas_leituras_alter_despesa_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituragas',
            name='leitura',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
